
import type { Alumni, Book, Course, Editorial, Faculty, QuizMark, Room, Student, StudentResult, AuditLog } from '@/lib/types';

export const mockStudents: Student[] = [
  { id: 'S001', name: 'Aarav Sharma', branch: 'Computer Science', year: 3, major: 'Computer Science', minor: 'Data Science', electiveChoices: ['CS302', 'CS301', 'DS301'], enrolledCredits: 21, preferredTimeSlots: ["10:00 - 11:00", "02:00 - 03:00"] },
  { id: 'S002', name: 'Vivaan Singh', branch: 'Electronics', year: 2, major: 'Electronics', minor: 'Embedded Systems', electiveChoices: ['EC202', 'ES201'], enrolledCredits: 18, preferredTimeSlots: ["09:00 - 10:00"] },
  { id: 'S003', name: 'Aditya Patel', branch: 'Mechanical', year: 4, major: 'Mechanical', minor: 'Robotics', electiveChoices: ['ME401'], enrolledCredits: 22, preferredTimeSlots: ["11:00 - 12:00", "03:00 - 04:00"] },
  { id: 'S004', name: 'Vihaan Verma', branch: 'Computer Science', year: 2, major: 'Computer Science', minor: 'Web Development', electiveChoices: ['CS205'], enrolledCredits: 20, preferredTimeSlots: ["10:00 - 11:00"] },
  { id: 'S005', name: 'Arjun Jha', branch: 'Electrical', year: 3, major: 'Electrical', minor: 'Control Systems', electiveChoices: ['EE302'], enrolledCredits: 19, preferredTimeSlots: ["04:00 - 05:00"] },
  { id: 'S006', name: 'Sai Gupta', branch: 'Civil', year: 4, major: 'Civil Engineering', minor: 'Environmental Engg', electiveChoices: ['PH100'], enrolledCredits: 23, preferredTimeSlots: ["10:00 - 11:00"] },
  { id: 'S007', name: 'Reyansh Kumar', branch: 'Mechanical', year: 1, major: 'Mechanical', minor: 'Robotics', electiveChoices: ['HS101'], enrolledCredits: 17, preferredTimeSlots: ["09:00 - 10:00", "11:00 - 12:00"] },
  { id: 'S008', name: 'Ayaan Reddy', branch: 'Electronics', year: 3, major: 'Electronics', minor: 'Embedded Systems', electiveChoices: ['EC301', 'ES201'], enrolledCredits: 20, preferredTimeSlots: ["02:00 - 03:00"] },
  { id: 'S009', name: 'Krishna Iyer', branch: 'Computer Science', year: 1, major: 'Computer Science', minor: 'Data Science', electiveChoices: ['CS301'], enrolledCredits: 18, preferredTimeSlots: ["10:00 - 11:00"] },
  { id: 'S010', name: 'Ishaan Rathod', branch: 'Biotechnology', year: 2, major: 'Biotechnology', minor: 'Genetics', electiveChoices: ['PH100'], enrolledCredits: 19, preferredTimeSlots: ["12:00 - 01:00"] },
  { id: 'S011', name: 'Rohan Mehra', branch: 'Computer Science', year: 3, major: 'Computer Science', minor: 'Data Science', electiveChoices: ['CS302', 'DS301'], enrolledCredits: 21, preferredTimeSlots: ["10:00 - 11:00", "02:00 - 03:00"] },
  { id: 'S012', name: 'Priya Agarwal', branch: 'Electronics', year: 1, major: 'Electronics', minor: 'Embedded Systems', electiveChoices: ['EC202'], enrolledCredits: 18, preferredTimeSlots: ["09:00 - 10:00"] },
  { id: 'S013', name: 'Amit Desai', branch: 'Mechanical', year: 4, major: 'Mechanical', minor: 'Robotics', electiveChoices: ['ME401'], enrolledCredits: 22, preferredTimeSlots: ["11:00 - 12:00", "03:00 - 04:00"] },
  { id: 'S014', name: 'Sneha Khan', branch: 'Computer Science', year: 2, major: 'Computer Science', minor: 'Web Development', electiveChoices: ['CS205'], enrolledCredits: 20, preferredTimeSlots: ["10:00 - 11:00"] },
  { id: 'S015', name: 'Karan Malhotra', branch: 'Electrical', year: 3, major: 'Electrical', minor: 'Control Systems', electiveChoices: ['EE302'], enrolledCredits: 19, preferredTimeSlots: ["04:00 - 05:00"] },
  { id: 'S016', name: 'Ananya Joshi', branch: 'Civil', year: 2, major: 'Civil Engineering', minor: 'Environmental Engg', electiveChoices: ['HS101'], enrolledCredits: 19, preferredTimeSlots: ["02:00 - 03:00"] },
  { id: 'S017', name: 'Vikram Nair', branch: 'Mechanical', year: 1, major: 'Mechanical', minor: 'Robotics', electiveChoices: ['PH100'], enrolledCredits: 17, preferredTimeSlots: ["09:00 - 10:00", "11:00 - 12:00"] },
  { id: 'S018', name: 'Natasha Menon', branch: 'Electronics', year: 3, major: 'Electronics', minor: 'Embedded Systems', electiveChoices: ['EC301', 'ES201'], enrolledCredits: 20, preferredTimeSlots: ["02:00 - 03:00"] },
  { id: 'S019', name: 'Rahul Pillai', branch: 'Computer Science', year: 4, major: 'Computer Science', minor: 'Data Science', electiveChoices: ['CS302', 'DS301'], enrolledCredits: 24, preferredTimeSlots: ["10:00 - 11:00"] },
  { id: 'S020', name: 'Aryan Jain', branch: 'Biotechnology', year: 2, major: 'Biotechnology', minor: 'Genetics', electiveChoices: ['HS101'], enrolledCredits: 19, preferredTimeSlots: ["12:00 - 01:00"] },
  { id: 'S021', name: 'Siddharth Shah', branch: 'Computer Science', year: 3, major: 'Computer Science', minor: 'Data Science', electiveChoices: ['CS301', 'DS301'], enrolledCredits: 21, preferredTimeSlots: ["10:00 - 11:00", "02:00 - 03:00"] },
  { id: 'S022', name: 'Meera Chaudhary', branch: 'Electronics', year: 2, major: 'Electronics', minor: 'Embedded Systems', electiveChoices: ['EC202', 'ES201'], enrolledCredits: 18, preferredTimeSlots: ["09:00 - 10:00"] },
  { id: 'S023', name: 'Anika Reddy', branch: 'Mechanical', year: 4, major: 'Mechanical', minor: 'Robotics', electiveChoices: ['ME401'], enrolledCredits: 22, preferredTimeSlots: ["11:00 - 12:00", "03:00 - 04:00"] },
  { id: 'S024', name: 'Ishita Verma', branch: 'Computer Science', year: 1, major: 'Computer Science', minor: 'Web Development', electiveChoices: ['CS205'], enrolledCredits: 18, preferredTimeSlots: ["10:00 - 11:00"] },
  { id: 'S025', name: 'Zara Khan', branch: 'Electrical', year: 3, major: 'Electrical', minor: 'Control Systems', electiveChoices: ['EE302'], enrolledCredits: 19, preferredTimeSlots: ["04:00 - 05:00"] },
  { id: 'S026', name: 'Kavya Singh', branch: 'Civil', year: 4, major: 'Civil Engineering', minor: 'Environmental Engg', electiveChoices: ['PH100'], enrolledCredits: 23, preferredTimeSlots: ["09:00 - 10:00"] },
  { id: 'S027', name: 'Fatima Ahmed', branch: 'Mechanical', year: 2, major: 'Mechanical', minor: 'Robotics', electiveChoices: ['ME301'], enrolledCredits: 20, preferredTimeSlots: ["09:00 - 10:00", "11:00 - 12:00"] },
  { id: 'S028', name: 'Jay Patel', branch: 'Electronics', year: 3, major: 'Electronics', minor: 'Embedded Systems', electiveChoices: ['EC301', 'ES201'], enrolledCredits: 20, preferredTimeSlots: ["02:00 - 03:00"] },
  { id: 'S029', name: 'Kabir Kumar', branch: 'Computer Science', year: 1, major: 'Computer Science', minor: 'Data Science', electiveChoices: ['CS301'], enrolledCredits: 18, preferredTimeSlots: ["10:00 - 11:00"] },
  { id: 'S030', name: 'Myra Das', branch: 'Biotechnology', year: 2, major: 'Biotechnology', minor: 'Genetics', electiveChoices: ['HS101'], enrolledCredits: 19, preferredTimeSlots: ["12:00 - 01:00"] },
  { id: 'S031', name: 'Diya Gupta', branch: 'Computer Science', year: 4, major: 'Computer Science', minor: 'Data Science', electiveChoices: ['CS302', 'DS301'], enrolledCredits: 24, preferredTimeSlots: ["10:00 - 11:00", "02:00 - 03:00"] },
  { id: 'S032', name: 'Aryan Mishra', branch: 'Electronics', year: 1, major: 'Electronics', minor: 'Embedded Systems', electiveChoices: ['EC202'], enrolledCredits: 18, preferredTimeSlots: ["09:00 - 10:00"] },
  { id: 'S033', name: 'Advik Tiwari', branch: 'Mechanical', year: 3, major: 'Mechanical', minor: 'Robotics', electiveChoices: ['ME301'], enrolledCredits: 21, preferredTimeSlots: ["11:00 - 12:00", "03:00 - 04:00"] },
  { id: 'S034', name: 'Anvi Pandey', branch: 'Computer Science', year: 2, major: 'Computer Science', minor: 'Web Development', electiveChoices: ['CS205'], enrolledCredits: 20, preferredTimeSlots: ["10:00 - 11:00"] },
  { id: 'S035', name: 'Aarush Bhat', branch: 'Electrical', year: 4, major: 'Electrical', minor: 'Control Systems', electiveChoices: ['EE302'], enrolledCredits: 23, preferredTimeSlots: ["04:00 - 05:00"] },
  { id: 'S036', name: 'Kiara Hegde', branch: 'Civil', year: 1, major: 'Civil Engineering', minor: 'Environmental Engg', electiveChoices: ['HS101'], enrolledCredits: 17, preferredTimeSlots: ["11:00 - 12:00"] },
  { id: 'S037', name: 'Veer Shetty', branch: 'Mechanical', year: 3, major: 'Mechanical', minor: 'Robotics', electiveChoices: ['ME401'], enrolledCredits: 21, preferredTimeSlots: ["09:00 - 10:00", "11:00 - 12:00"] },
  { id: 'S038', name: 'Samaira Rao', branch: 'Electronics', year: 2, major: 'Electronics', minor: 'Embedded Systems', electiveChoices: ['EC301', 'ES201'], enrolledCredits: 18, preferredTimeSlots: ["02:00 - 03:00"] },
  { id: 'S039', name: 'Zoya Agarwal', branch: 'Computer Science', year: 4, major: 'Computer Science', minor: 'Data Science', electiveChoices: ['CS301', 'CS302', 'DS301'], enrolledCredits: 25, preferredTimeSlots: ["10:00 - 11:00"] },
  { id: 'S040', name: 'Dhruv Bajaj', branch: 'Biotechnology', year: 1, major: 'Biotechnology', minor: 'Genetics', electiveChoices: ['PH100'], enrolledCredits: 17, preferredTimeSlots: ["12:00 - 01:00"] },
  { id: 'S041', name: 'Riya Sharma', branch: 'Computer Science', year: 2, major: 'Computer Science', minor: 'Web Development', electiveChoices: ['CS205'], enrolledCredits: 20, preferredTimeSlots: ["10:00 - 11:00", "02:00 - 03:00"] },
  { id: 'S042', name: 'Arnav Singh', branch: 'Electronics', year: 4, major: 'Electronics', minor: 'Embedded Systems', electiveChoices: ['EC301', 'ES201'], enrolledCredits: 21, preferredTimeSlots: ["09:00 - 10:00"] },
  { id: 'S043', name: 'Isha Patel', branch: 'Mechanical', year: 1, major: 'Mechanical', minor: 'Robotics', electiveChoices: ['HS101'], enrolledCredits: 18, preferredTimeSlots: ["11:00 - 12:00", "03:00 - 04:00"] },
  { id: 'S044', name: 'Yash Verma', branch: 'Computer Science', year: 3, major: 'Computer Science', minor: 'Data Science', electiveChoices: ['CS301', 'DS301'], enrolledCredits: 22, preferredTimeSlots: ["10:00 - 11:00"] },
  { id: 'S045', name: 'Anaya Jha', branch: 'Electrical', year: 2, major: 'Electrical', minor: 'Control Systems', electiveChoices: ['EE302'], enrolledCredits: 19, preferredTimeSlots: ["04:00 - 05:00"] },
  { id: 'S046', name: 'Nikhil Gupta', branch: 'Civil', year: 3, major: 'Civil Engineering', minor: 'Environmental Engg', electiveChoices: ['PH100'], enrolledCredits: 20, preferredTimeSlots: ["03:00 - 04:00"] },
  { id: 'S047', name: 'Parth Kumar', branch: 'Mechanical', year: 4, major: 'Mechanical', minor: 'Robotics', electiveChoices: ['HS101'], enrolledCredits: 23, preferredTimeSlots: ["09:00 - 10:00", "11:00 - 12:00"] },
  { id: 'S048', name: 'Saanvi Reddy', branch: 'Electronics', year: 1, major: 'Electronics', minor: 'Embedded Systems', electiveChoices: ['EC202'], enrolledCredits: 17, preferredTimeSlots: ["02:00 - 03:00"] },
  { id: 'S049', name: 'Dev Iyer', branch: 'Computer Science', year: 2, major: 'Computer Science', minor: 'Data Science', electiveChoices: ['CS302'], enrolledCredits: 20, preferredTimeSlots: ["10:00 - 11:00"] },
  { id: 'S050', name: 'Aadhya Rathod', branch: 'Biotechnology', year: 3, major: 'Biotechnology', minor: 'Genetics', electiveChoices: ['PH100'], enrolledCredits: 21, preferredTimeSlots: ["12:00 - 01:00"] },
  { id: 'S051', name: 'Alia Bhatt', branch: 'B.Ed.', year: 1, major: 'Education', minor: 'English Literature', electiveChoices: ['ED101', 'EL101'], enrolledCredits: 18, preferredTimeSlots: [] },
  { id: 'S052', name: 'Ranbir Kapoor', branch: 'B.Ed.', year: 2, major: 'Education', minor: 'History', electiveChoices: ['ED201', 'HY201'], enrolledCredits: 20, preferredTimeSlots: [] },
  { id: 'S053', name: 'Deepika Padukone', branch: 'ITEP', year: 3, major: 'Integrated Teacher Education', minor: 'Mathematics', electiveChoices: ['IT301', 'MA301'], enrolledCredits: 22, preferredTimeSlots: [] },
  { id: 'S054', name: 'Ranveer Singh', branch: 'ITEP', year: 4, major: 'Integrated Teacher Education', minor: 'Physics', electiveChoices: ['IT401', 'PH401'], enrolledCredits: 21, preferredTimeSlots: [] },
  // Additional 50 students for better representation
  { id: 'S055', name: 'Akshay Kumar', branch: 'Computer Science', year: 1, major: 'Computer Science', minor: 'Data Science', electiveChoices: ['CS301'], enrolledCredits: 18, preferredTimeSlots: ["09:00 - 10:00"] },
  { id: 'S056', name: 'Katrina Kaif', branch: 'Electronics', year: 2, major: 'Electronics', minor: 'Embedded Systems', electiveChoices: ['EC202'], enrolledCredits: 19, preferredTimeSlots: ["10:00 - 11:00"] },
  { id: 'S057', name: 'Salman Khan', branch: 'Mechanical', year: 3, major: 'Mechanical', minor: 'Robotics', electiveChoices: ['ME301'], enrolledCredits: 21, preferredTimeSlots: ["11:00 - 12:00"] },
  { id: 'S058', name: 'Kareena Kapoor', branch: 'Computer Science', year: 4, major: 'Computer Science', minor: 'Web Development', electiveChoices: ['CS205', 'CS405'], enrolledCredits: 24, preferredTimeSlots: ["02:00 - 03:00"] },
  { id: 'S059', name: 'Shah Rukh Khan', branch: 'Electrical', year: 2, major: 'Electrical', minor: 'Control Systems', electiveChoices: ['EE302'], enrolledCredits: 18, preferredTimeSlots: ["03:00 - 04:00"] },
  { id: 'S060', name: 'Priyanka Chopra', branch: 'Civil', year: 1, major: 'Civil Engineering', minor: 'Environmental Engg', electiveChoices: ['HS101'], enrolledCredits: 17, preferredTimeSlots: ["04:00 - 05:00"] },
  { id: 'S061', name: 'Hrithik Roshan', branch: 'Biotechnology', year: 3, major: 'Biotechnology', minor: 'Genetics', electiveChoices: ['PH100'], enrolledCredits: 20, preferredTimeSlots: ["09:00 - 10:00"] },
  { id: 'S062', name: 'Aishwarya Rai', branch: 'Computer Science', year: 2, major: 'Computer Science', minor: 'Data Science', electiveChoices: ['CS302', 'DS301'], enrolledCredits: 21, preferredTimeSlots: ["10:00 - 11:00"] },
  { id: 'S063', name: 'Amitabh Bachchan', branch: 'Electronics', year: 4, major: 'Electronics', minor: 'Embedded Systems', electiveChoices: ['EC301', 'ES201'], enrolledCredits: 23, preferredTimeSlots: ["11:00 - 12:00"] },
  { id: 'S064', name: 'Madhuri Dixit', branch: 'Mechanical', year: 1, major: 'Mechanical', minor: 'Robotics', electiveChoices: ['HS101'], enrolledCredits: 18, preferredTimeSlots: ["02:00 - 03:00"] },
  { id: 'S065', name: 'Ajay Devgan', branch: 'Computer Science', year: 3, major: 'Computer Science', minor: 'Web Development', electiveChoices: ['CS301', 'CS205'], enrolledCredits: 22, preferredTimeSlots: ["03:00 - 04:00"] },
  { id: 'S066', name: 'Kajol Devgan', branch: 'Electrical', year: 2, major: 'Electrical', minor: 'Control Systems', electiveChoices: ['EE302'], enrolledCredits: 19, preferredTimeSlots: ["04:00 - 05:00"] },
  { id: 'S067', name: 'Sunny Deol', branch: 'Civil', year: 4, major: 'Civil Engineering', minor: 'Environmental Engg', electiveChoices: ['PH100'], enrolledCredits: 22, preferredTimeSlots: ["09:00 - 10:00"] },
  { id: 'S068', name: 'Juhi Chawla', branch: 'Biotechnology', year: 1, major: 'Biotechnology', minor: 'Genetics', electiveChoices: ['HS101'], enrolledCredits: 17, preferredTimeSlots: ["10:00 - 11:00"] },
  { id: 'S069', name: 'Bobby Deol', branch: 'Computer Science', year: 2, major: 'Computer Science', minor: 'Data Science', electiveChoices: ['CS302'], enrolledCredits: 20, preferredTimeSlots: ["11:00 - 12:00"] },
  { id: 'S070', name: 'Preity Zinta', branch: 'Electronics', year: 3, major: 'Electronics', minor: 'Embedded Systems', electiveChoices: ['EC301'], enrolledCredits: 21, preferredTimeSlots: ["02:00 - 03:00"] },
  { id: 'S071', name: 'Saif Ali Khan', branch: 'Mechanical', year: 4, major: 'Mechanical', minor: 'Robotics', electiveChoices: ['ME401'], enrolledCredits: 23, preferredTimeSlots: ["03:00 - 04:00"] },
  { id: 'S072', name: 'Karisma Kapoor', branch: 'Computer Science', year: 1, major: 'Computer Science', minor: 'Web Development', electiveChoices: ['CS205'], enrolledCredits: 18, preferredTimeSlots: ["04:00 - 05:00"] },
  { id: 'S073', name: 'Abhishek Bachchan', branch: 'Electrical', year: 3, major: 'Electrical', minor: 'Control Systems', electiveChoices: ['EE302'], enrolledCredits: 20, preferredTimeSlots: ["09:00 - 10:00"] },
  { id: 'S074', name: 'Rani Mukerji', branch: 'Civil', year: 2, major: 'Civil Engineering', minor: 'Environmental Engg', electiveChoices: ['HS101'], enrolledCredits: 19, preferredTimeSlots: ["10:00 - 11:00"] },
  { id: 'S075', name: 'John Abraham', branch: 'Biotechnology', year: 4, major: 'Biotechnology', minor: 'Genetics', electiveChoices: ['PH100'], enrolledCredits: 22, preferredTimeSlots: ["11:00 - 12:00"] },
  { id: 'S076', name: 'Bipasha Basu', branch: 'Computer Science', year: 2, major: 'Computer Science', minor: 'Data Science', electiveChoices: ['DS301'], enrolledCredits: 20, preferredTimeSlots: ["02:00 - 03:00"] },
  { id: 'S077', name: 'Emraan Hashmi', branch: 'Electronics', year: 1, major: 'Electronics', minor: 'Embedded Systems', electiveChoices: ['EC202'], enrolledCredits: 18, preferredTimeSlots: ["03:00 - 04:00"] },
  { id: 'S078', name: 'Vidya Balan', branch: 'Mechanical', year: 3, major: 'Mechanical', minor: 'Robotics', electiveChoices: ['ME301'], enrolledCredits: 21, preferredTimeSlots: ["04:00 - 05:00"] },
  { id: 'S079', name: 'Rajkummar Rao', branch: 'Computer Science', year: 4, major: 'Computer Science', minor: 'Web Development', electiveChoices: ['CS405'], enrolledCredits: 24, preferredTimeSlots: ["09:00 - 10:00"] },
  { id: 'S080', name: 'Kangana Ranaut', branch: 'Electrical', year: 1, major: 'Electrical', minor: 'Control Systems', electiveChoices: ['EE302'], enrolledCredits: 17, preferredTimeSlots: ["10:00 - 11:00"] },
  { id: 'S081', name: 'Ayushmann Khurrana', branch: 'Civil', year: 3, major: 'Civil Engineering', minor: 'Environmental Engg', electiveChoices: ['PH100'], enrolledCredits: 20, preferredTimeSlots: ["11:00 - 12:00"] },
  { id: 'S082', name: 'Shraddha Kapoor', branch: 'Biotechnology', year: 2, major: 'Biotechnology', minor: 'Genetics', electiveChoices: ['HS101'], enrolledCredits: 19, preferredTimeSlots: ["02:00 - 03:00"] },
  { id: 'S083', name: 'Kartik Aaryan', branch: 'Computer Science', year: 1, major: 'Computer Science', minor: 'Data Science', electiveChoices: ['CS301'], enrolledCredits: 18, preferredTimeSlots: ["03:00 - 04:00"] },
  { id: 'S084', name: 'Kiara Advani', branch: 'Electronics', year: 4, major: 'Electronics', minor: 'Embedded Systems', electiveChoices: ['EC301', 'ES201'], enrolledCredits: 23, preferredTimeSlots: ["04:00 - 05:00"] },
  { id: 'S085', name: 'Varun Dhawan', branch: 'Mechanical', year: 2, major: 'Mechanical', minor: 'Robotics', electiveChoices: ['ME301'], enrolledCredits: 20, preferredTimeSlots: ["09:00 - 10:00"] },
  { id: 'S086', name: 'Alia Bhatt Jr', branch: 'Computer Science', year: 3, major: 'Computer Science', minor: 'Web Development', electiveChoices: ['CS302', 'CS205'], enrolledCredits: 22, preferredTimeSlots: ["10:00 - 11:00"] },
  { id: 'S087', name: 'Sidharth Malhotra', branch: 'Electrical', year: 4, major: 'Electrical', minor: 'Control Systems', electiveChoices: ['EE302'], enrolledCredits: 21, preferredTimeSlots: ["11:00 - 12:00"] },
  { id: 'S088', name: 'Jacqueline Fernandez', branch: 'Civil', year: 1, major: 'Civil Engineering', minor: 'Environmental Engg', electiveChoices: ['HS101'], enrolledCredits: 17, preferredTimeSlots: ["02:00 - 03:00"] },
  { id: 'S089', name: 'Tiger Shroff', branch: 'Biotechnology', year: 3, major: 'Biotechnology', minor: 'Genetics', electiveChoices: ['PH100'], enrolledCredits: 20, preferredTimeSlots: ["03:00 - 04:00"] },
  { id: 'S090', name: 'Disha Patani', branch: 'Computer Science', year: 2, major: 'Computer Science', minor: 'Data Science', electiveChoices: ['CS302', 'DS301'], enrolledCredits: 21, preferredTimeSlots: ["04:00 - 05:00"] },
  { id: 'S091', name: 'Arjun Kapoor', branch: 'Electronics', year: 1, major: 'Electronics', minor: 'Embedded Systems', electiveChoices: ['EC202'], enrolledCredits: 18, preferredTimeSlots: ["09:00 - 10:00"] },
  { id: 'S092', name: 'Parineeti Chopra', branch: 'Mechanical', year: 4, major: 'Mechanical', minor: 'Robotics', electiveChoices: ['ME401'], enrolledCredits: 23, preferredTimeSlots: ["10:00 - 11:00"] },
  { id: 'S093', name: 'Randeep Hooda', branch: 'Computer Science', year: 3, major: 'Computer Science', minor: 'Web Development', electiveChoices: ['CS301', 'CS205'], enrolledCredits: 22, preferredTimeSlots: ["11:00 - 12:00"] },
  { id: 'S094', name: 'Sonakshi Sinha', branch: 'Electrical', year: 2, major: 'Electrical', minor: 'Control Systems', electiveChoices: ['EE302'], enrolledCredits: 19, preferredTimeSlots: ["02:00 - 03:00"] },
  { id: 'S095', name: 'Sushant Singh', branch: 'Civil', year: 4, major: 'Civil Engineering', minor: 'Environmental Engg', electiveChoices: ['PH100'], enrolledCredits: 22, preferredTimeSlots: ["03:00 - 04:00"] },
  { id: 'S096', name: 'Kriti Sanon', branch: 'Biotechnology', year: 1, major: 'Biotechnology', minor: 'Genetics', electiveChoices: ['HS101'], enrolledCredits: 17, preferredTimeSlots: ["04:00 - 05:00"] },
  { id: 'S097', name: 'Shahid Kapoor', branch: 'Computer Science', year: 2, major: 'Computer Science', minor: 'Data Science', electiveChoices: ['CS302'], enrolledCredits: 20, preferredTimeSlots: ["09:00 - 10:00"] },
  { id: 'S098', name: 'Mira Rajput', branch: 'Electronics', year: 3, major: 'Electronics', minor: 'Embedded Systems', electiveChoices: ['EC301'], enrolledCredits: 21, preferredTimeSlots: ["10:00 - 11:00"] },
  { id: 'S099', name: 'Vicky Kaushal', branch: 'Mechanical', year: 4, major: 'Mechanical', minor: 'Robotics', electiveChoices: ['ME401'], enrolledCredits: 23, preferredTimeSlots: ["11:00 - 12:00"] },
  { id: 'S100', name: 'Yami Gautam', branch: 'Computer Science', year: 1, major: 'Computer Science', minor: 'Web Development', electiveChoices: ['CS205'], enrolledCredits: 18, preferredTimeSlots: ["02:00 - 03:00"] },
  // Education students
  { id: 'S101', name: 'Taapsee Pannu', branch: 'B.Ed.', year: 1, major: 'Education', minor: 'Mathematics', electiveChoices: ['ED101', 'MA301'], enrolledCredits: 18, preferredTimeSlots: [] },
  { id: 'S102', name: 'Bhumi Pednekar', branch: 'B.Ed.', year: 2, major: 'Education', minor: 'Science', electiveChoices: ['ED201', 'PH401'], enrolledCredits: 20, preferredTimeSlots: [] },
  { id: 'S103', name: 'Rajkummar Hirani', branch: 'ITEP', year: 3, major: 'Integrated Teacher Education', minor: 'English', electiveChoices: ['IT301', 'EL101'], enrolledCredits: 22, preferredTimeSlots: [] },
  { id: 'S104', name: 'Anushka Sharma', branch: 'ITEP', year: 4, major: 'Integrated Teacher Education', minor: 'History', electiveChoices: ['IT401', 'HY201'], enrolledCredits: 21, preferredTimeSlots: [] },
  { id: 'S105', name: 'Virat Kohli', branch: 'B.Ed.', year: 2, major: 'Education', minor: 'Physical Education', electiveChoices: ['ED201'], enrolledCredits: 19, preferredTimeSlots: [] },
];

export const mockFaculty: Faculty[] = [
  { id: 'F01', name: 'Dr. Anil Kumar', department: 'Computer Science', almaMater: 'IIT Delhi', specialization: 'Algorithms, AI', workload: 10, studentFeedback: 4.8 },
  { id: 'F02', name: 'Dr. Sunita Reddy', department: 'Electronics', almaMater: 'IIT Bombay', specialization: 'VLSI, Embedded Systems', workload: 12, studentFeedback: 4.6 },
  { id: 'F03', name: 'Dr. Rajesh Gupta', department: 'Mechanical', almaMater: 'IIT Kanpur', specialization: 'Thermodynamics, Fluid Mechanics', workload: 8, studentFeedback: 4.5 },
  { id: 'F04', name: 'Dr. Meera Iyer', department: 'Computer Science', almaMater: 'Stanford University', specialization: 'Database Systems, Compilers, Data Structures', workload: 15, studentFeedback: 4.9 },
  { id: 'F05', name: 'Dr. Vikram Rathod', department: 'Electrical', almaMater: 'IIT Madras', specialization: 'Power Systems, Control Systems', workload: 9, studentFeedback: 4.3 },
  { id: 'F06', name: 'Prof. Alok Nath', department: 'Humanities', almaMater: 'JNU', specialization: 'Linguistics, Communication', workload: 14, studentFeedback: 4.7 },
  { id: 'F07', name: 'Dr. Priya Sharma', department: 'Physics', almaMater: 'IISc Bangalore', specialization: 'Quantum Mechanics, Optics', workload: 11, studentFeedback: 4.4 },
  { id: 'F08', name: 'Dr. Karan Johar', department: 'Education', almaMater: 'University of Delhi', specialization: 'Pedagogy, Curriculum Design', workload: 10, studentFeedback: 4.8 },
  // Additional 25 faculty members for comprehensive coverage
  { id: 'F09', name: 'Dr. Arjun Kapoor', department: 'Computer Science', almaMater: 'MIT', specialization: 'Machine Learning, Neural Networks', workload: 12, studentFeedback: 4.9 },
  { id: 'F10', name: 'Dr. Deepika Singh', department: 'Electronics', almaMater: 'IIT Guwahati', specialization: 'Signal Processing, Communications', workload: 11, studentFeedback: 4.7 },
  { id: 'F11', name: 'Prof. Shahid Mallya', department: 'Mechanical', almaMater: 'IIT Roorkee', specialization: 'Manufacturing, CAD/CAM', workload: 10, studentFeedback: 4.6 },
  { id: 'F12', name: 'Dr. Katrina Verma', department: 'Computer Science', almaMater: 'Carnegie Mellon', specialization: 'Software Engineering, Distributed Systems', workload: 13, studentFeedback: 4.8 },
  { id: 'F13', name: 'Dr. Salman Ahmed', department: 'Electrical', almaMater: 'IIT Kharagpur', specialization: 'Renewable Energy, Smart Grids', workload: 9, studentFeedback: 4.5 },
  { id: 'F14', name: 'Prof. Kareena Joshi', department: 'Civil', almaMater: 'IIT Delhi', specialization: 'Structural Engineering, Construction Management', workload: 8, studentFeedback: 4.4 },
  { id: 'F15', name: 'Dr. Hrithik Patel', department: 'Biotechnology', almaMater: 'IISc Bangalore', specialization: 'Genetic Engineering, Bioinformatics', workload: 11, studentFeedback: 4.6 },
  { id: 'F16', name: 'Dr. Priyanka Das', department: 'Computer Science', almaMater: 'UC Berkeley', specialization: 'Computer Vision, Image Processing', workload: 14, studentFeedback: 4.9 },
  { id: 'F17', name: 'Prof. Akshay Nair', department: 'Electronics', almaMater: 'IIT Hyderabad', specialization: 'Microelectronics, Nanotechnology', workload: 10, studentFeedback: 4.7 },
  { id: 'F18', name: 'Dr. Aishwarya Roy', department: 'Mechanical', almaMater: 'Georgia Tech', specialization: 'Robotics, Automation', workload: 12, studentFeedback: 4.8 },
  { id: 'F19', name: 'Dr. Ranveer Kumar', department: 'Computer Science', almaMater: 'Oxford University', specialization: 'Cybersecurity, Blockchain', workload: 13, studentFeedback: 4.9 },
  { id: 'F20', name: 'Prof. Alia Gupta', department: 'Electrical', almaMater: 'IIT Bombay', specialization: 'Electronics Design, IoT', workload: 9, studentFeedback: 4.6 },
  { id: 'F21', name: 'Dr. Varun Mehta', department: 'Civil', almaMater: 'IIT Kanpur', specialization: 'Environmental Engineering, Water Resources', workload: 8, studentFeedback: 4.5 },
  { id: 'F22', name: 'Dr. Kiara Reddy', department: 'Biotechnology', almaMater: 'Harvard University', specialization: 'Molecular Biology, Cell Biology', workload: 11, studentFeedback: 4.8 },
  { id: 'F23', name: 'Prof. Sidharth Sharma', department: 'Computer Science', almaMater: 'Stanford University', specialization: 'Cloud Computing, Big Data', workload: 14, studentFeedback: 4.7 },
  { id: 'F24', name: 'Dr. Jacqueline Iyer', department: 'Electronics', almaMater: 'Caltech', specialization: 'Quantum Electronics, Photonics', workload: 12, studentFeedback: 4.9 },
  { id: 'F25', name: 'Dr. Tiger Jain', department: 'Mechanical', almaMater: 'ETH Zurich', specialization: 'Aerospace Engineering, Dynamics', workload: 10, studentFeedback: 4.6 },
  { id: 'F26', name: 'Prof. Disha Agarwal', department: 'Computer Science', almaMater: 'Cambridge University', specialization: 'Human-Computer Interaction, UX Design', workload: 13, studentFeedback: 4.8 },
  { id: 'F27', name: 'Dr. Ayushmann Verma', department: 'Electrical', almaMater: 'IIT Roorkee', specialization: 'Power Electronics, Motor Drives', workload: 9, studentFeedback: 4.5 },
  { id: 'F28', name: 'Dr. Shraddha Singh', department: 'Civil', almaMater: 'University of Toronto', specialization: 'Transportation Engineering, Urban Planning', workload: 8, studentFeedback: 4.4 },
  { id: 'F29', name: 'Prof. Kartik Malhotra', department: 'Biotechnology', almaMater: 'Johns Hopkins', specialization: 'Biomedical Engineering, Drug Design', workload: 11, studentFeedback: 4.7 },
  { id: 'F30', name: 'Dr. Ananya Kulkarni', department: 'Computer Science', almaMater: 'MIT', specialization: 'Artificial Intelligence, Robotics', workload: 15, studentFeedback: 4.9 },
  { id: 'F31', name: 'Prof. Rajkummar Desai', department: 'Electronics', almaMater: 'IIT Madras', specialization: 'RF Engineering, Antenna Design', workload: 10, studentFeedback: 4.6 },
  { id: 'F32', name: 'Dr. Vidya Bose', department: 'Mechanical', almaMater: 'University of Michigan', specialization: 'Heat Transfer, Energy Systems', workload: 12, studentFeedback: 4.8 },
  { id: 'F33', name: 'Dr. Vicky Rao', department: 'Education', almaMater: 'Teachers College Columbia', specialization: 'Educational Psychology, Learning Theory', workload: 10, studentFeedback: 4.7 },
  // Education Faculty
  { id: 'F34', name: 'Prof. Taapsee Khanna', department: 'Education', almaMater: 'University of Cambridge', specialization: 'Curriculum Development, Assessment', workload: 12, studentFeedback: 4.8 },
  { id: 'F35', name: 'Dr. Bhumi Trivedi', department: 'Education', almaMater: 'Harvard Graduate School', specialization: 'Special Education, Inclusive Teaching', workload: 11, studentFeedback: 4.9 },
];

export const mockCourses: Course[] = [
  { id: 'CS301', name: 'Data Structures', code: 'CS301', credits: 4, type: 'Hybrid', category: 'Major', capacity: 60, program: 'B.Tech', classes: [
    { id: 'CS301-1', name: 'CSE-1', capacity: 30, year: 3, section: 'A' },
    { id: 'CS301-2', name: 'CSE-2', capacity: 30, year: 3, section: 'B' }
  ]},
  { id: 'EC202', name: 'Digital Circuits', code: 'EC202', credits: 3, type: 'Theory', category: 'Major', capacity: 70, program: 'B.Tech', classes: [
    { id: 'EC202-1', name: 'ECE-1', capacity: 35, year: 2, section: 'A' },
    { id: 'EC202-2', name: 'ECE-2', capacity: 35, year: 2, section: 'B' }
  ]},
  { id: 'ME401', name: 'Thermodynamics', code: 'ME401', credits: 4, type: 'Theory', category: 'Major', capacity: 80, program: 'B.Tech', classes: [
    { id: 'ME401-1', name: 'ME-1', capacity: 40, year: 4, section: 'A' },
    { id: 'ME401-2', name: 'ME-2', capacity: 40, year: 4, section: 'B' }
  ]},
  { id: 'CS302', name: 'Algorithms', code: 'CS302', credits: 4, type: 'Theory', category: 'Major', capacity: 60, program: 'B.Tech', classes: [
    { id: 'CS302-1', name: 'CSE-1', capacity: 30, year: 3, section: 'A' },
    { id: 'CS302-2', name: 'CSE-2', capacity: 30, year: 3, section: 'B' }
  ]},
  { id: 'EC301', name: 'Microprocessors', code: 'EC301', credits: 3, type: 'Practical', category: 'Major', capacity: 40, program: 'B.Tech', classes: [
    { id: 'EC301-1', name: 'ECE-1', capacity: 20, year: 3, section: 'A' },
    { id: 'EC301-2', name: 'ECE-2', capacity: 20, year: 3, section: 'B' }
  ]},
  { id: 'ME301', name: 'Fluid Mechanics', code: 'ME301', credits: 4, type: 'Theory', category: 'Major', capacity: 75, program: 'B.Tech', classes: [
    { id: 'ME301-1', name: 'ME-1', capacity: 37, year: 3, section: 'A' },
    { id: 'ME301-2', name: 'ME-2', capacity: 38, year: 3, section: 'B' }
  ]},
  { id: 'CS205', name: 'Web Development', code: 'CS205', credits: 3, type: 'Hybrid', category: 'Skill', capacity: 50, program: 'B.Tech', classes: [
    { id: 'CS205-1', name: 'CSE-Mixed', capacity: 50, year: 2, section: 'All' }
  ]},
  { id: 'EE302', name: 'Power Electronics', code: 'EE302', credits: 4, type: 'Practical', category: 'Major', capacity: 35, program: 'B.Tech', classes: [
    { id: 'EE302-1', name: 'EE-1', capacity: 35, year: 3, section: 'A' }
  ]},
  { id: 'HS101', name: 'Creative Writing', code: 'HS101', credits: 2, type: 'Theory', category: 'ValueAdded', capacity: 150, program: 'FYUP', classes: [
    { id: 'HS101-1', name: 'All-Years-Section-A', capacity: 75, section: 'A' },
    { id: 'HS101-2', name: 'All-Years-Section-B', capacity: 75, section: 'B' }
  ]},
  { id: 'PH100', name: 'Engineering Physics', code: 'PH100', credits: 3, type: 'Practical', category: 'Common', capacity: 100, program: 'FYUP', classes: [
    { id: 'PH100-1', name: 'Year-1-Section-A', capacity: 50, year: 1, section: 'A' },
    { id: 'PH100-2', name: 'Year-1-Section-B', capacity: 50, year: 1, section: 'B' }
  ]},
  { id: 'DS301', name: 'Intro to Data Science', code: 'DS301', credits: 3, type: 'Hybrid', category: 'Minor', capacity: 45, program: 'B.Tech', classes: [
    { id: 'DS301-1', name: 'DS-Mixed', capacity: 45, section: 'All' }
  ]},
  { id: 'ES201', name: 'Embedded Systems Design', code: 'ES201', credits: 3, type: 'Practical', category: 'Minor', capacity: 40, program: 'B.Tech', classes: [
    { id: 'ES201-1', name: 'ES-Mixed', capacity: 40, section: 'All' }
  ]},
  { id: 'ROB401', name: 'Intro to Robotics', code: 'ROB401', credits: 3, type: 'Hybrid', category: 'Minor', capacity: 30, program: 'B.Tech', classes: [
    { id: 'ROB401-1', name: 'ROB-Mixed', capacity: 30, section: 'All' }
  ]},
  { id: 'CS405', name: 'Machine Learning', code: 'CS405', credits: 4, type: 'Hybrid', category: 'Major', capacity: 50, program: 'B.Tech', classes: [
    { id: 'CS405-1', name: 'CSE-Advanced', capacity: 50, year: 4, section: 'All' }
  ]},
  { id: 'ED101', name: 'Childhood and Growing Up', code: 'ED101', credits: 4, type: 'Theory', category: 'Major', capacity: 50, program: 'B.Ed.', classes: [
    { id: 'ED101-1', name: 'Year-1-Class-A', capacity: 25, year: 1, section: 'A' },
    { id: 'ED101-2', name: 'Year-1-Class-B', capacity: 25, year: 1, section: 'B' }
  ]},
  { id: 'ED201', name: 'Learning and Teaching', code: 'ED201', credits: 4, type: 'Theory', category: 'Major', capacity: 50, program: 'B.Ed.', classes: [
    { id: 'ED201-1', name: 'Year-2-Class-A', capacity: 25, year: 2, section: 'A' },
    { id: 'ED201-2', name: 'Year-2-Class-B', capacity: 25, year: 2, section: 'B' }
  ]},
  { id: 'IT301', name: 'Pedagogy of School Subject', code: 'IT301', credits: 3, type: 'Hybrid', category: 'Major', capacity: 50, program: 'ITEP', classes: [
    { id: 'IT301-1', name: 'Year-3-Class-A', capacity: 25, year: 3, section: 'A' },
    { id: 'IT301-2', name: 'Year-3-Class-B', capacity: 25, year: 3, section: 'B' }
  ]},
  { id: 'IT401', name: 'Gender, School and Society', code: 'IT401', credits: 3, type: 'Theory', category: 'Major', capacity: 50, program: 'ITEP', classes: [
    { id: 'IT401-1', name: 'Year-4-Class-A', capacity: 25, year: 4, section: 'A' },
    { id: 'IT401-2', name: 'Year-4-Class-B', capacity: 25, year: 4, section: 'B' }
  ]},
  { id: 'EL101', name: 'Introduction to English Literature', code: 'EL101', credits: 3, type: 'Theory', category: 'Minor', capacity: 60, program: 'B.Ed.', classes: [
    { id: 'EL101-1', name: 'English-Mixed', capacity: 60, section: 'All' }
  ]},
  { id: 'HY201', name: 'History of Modern India', code: 'HY201', credits: 3, type: 'Theory', category: 'Minor', capacity: 60, program: 'B.Ed.', classes: [
    { id: 'HY201-1', name: 'History-Mixed', capacity: 60, section: 'All' }
  ]},
  { id: 'MA301', name: 'Calculus for Teachers', code: 'MA301', credits: 3, type: 'Theory', category: 'Minor', capacity: 60, program: 'ITEP', classes: [
    { id: 'MA301-1', name: 'Math-Mixed', capacity: 60, section: 'All' }
  ]},
  { id: 'PH401', name: 'Physics in Everyday Life', code: 'PH401', credits: 3, type: 'Hybrid', category: 'Minor', capacity: 60, program: 'ITEP', classes: [
    { id: 'PH401-1', name: 'Physics-Mixed', capacity: 60, section: 'All' }
  ]},
];

export const mockRooms: Room[] = [
  { id: 'R101', name: 'CS Block 101', capacity: 70, type: 'Lecture' },
  { id: 'R102', name: 'EC Lab 1', capacity: 30, type: 'Lab' },
  { id: 'R103', name: 'Mech Hall', capacity: 120, type: 'Lecture' },
  { id: 'R104', name: 'CS Block 102', capacity: 60, type: 'Lecture' },
  { id: 'R105', name: 'EE Lab 2', capacity: 40, type: 'Lab' },
  { id: 'R106', name: 'Main Auditorium', capacity: 500, type: 'Lecture' },
  { id: 'LH-1', name: 'Lecture Hall 1', capacity: 150, type: 'Lecture' },
  { id: 'PHY-L1', name: 'Physics Lab 1', capacity: 40, type: 'Lab' },
  { id: 'ED-1', name: 'Education Hall 1', capacity: 60, type: 'Lecture' },
  // Additional 25 rooms for comprehensive coverage
  { id: 'R107', name: 'CS Block 103', capacity: 80, type: 'Lecture' },
  { id: 'R108', name: 'CS Lab 1', capacity: 35, type: 'Lab' },
  { id: 'R109', name: 'CS Lab 2', capacity: 35, type: 'Lab' },
  { id: 'R110', name: 'CS Block 104', capacity: 90, type: 'Lecture' },
  { id: 'R111', name: 'EC Block 201', capacity: 75, type: 'Lecture' },
  { id: 'R112', name: 'EC Lab 2', capacity: 30, type: 'Lab' },
  { id: 'R113', name: 'EC Lab 3', capacity: 25, type: 'Lab' },
  { id: 'R114', name: 'EC Block 202', capacity: 85, type: 'Lecture' },
  { id: 'R115', name: 'Mech Block 301', capacity: 100, type: 'Lecture' },
  { id: 'R116', name: 'Mech Lab 1', capacity: 40, type: 'Lab' },
  { id: 'R117', name: 'Mech Lab 2', capacity: 35, type: 'Lab' },
  { id: 'R118', name: 'Mech Workshop', capacity: 50, type: 'Lab' },
  { id: 'R119', name: 'EE Block 401', capacity: 70, type: 'Lecture' },
  { id: 'R120', name: 'EE Lab 3', capacity: 30, type: 'Lab' },
  { id: 'R121', name: 'EE Lab 4', capacity: 35, type: 'Lab' },
  { id: 'R122', name: 'EE Block 402', capacity: 80, type: 'Lecture' },
  { id: 'R123', name: 'Civil Block 501', capacity: 90, type: 'Lecture' },
  { id: 'R124', name: 'Civil Lab 1', capacity: 40, type: 'Lab' },
  { id: 'R125', name: 'Civil Lab 2', capacity: 45, type: 'Lab' },
  { id: 'R126', name: 'Biotech Block 601', capacity: 60, type: 'Lecture' },
  { id: 'R127', name: 'Biotech Lab 1', capacity: 25, type: 'Lab' },
  { id: 'R128', name: 'Biotech Lab 2', capacity: 30, type: 'Lab' },
  { id: 'LH-2', name: 'Lecture Hall 2', capacity: 180, type: 'Lecture' },
  { id: 'LH-3', name: 'Lecture Hall 3', capacity: 200, type: 'Lecture' },
  { id: 'LH-4', name: 'Lecture Hall 4', capacity: 160, type: 'Lecture' },
  { id: 'LH-5', name: 'Lecture Hall 5', capacity: 140, type: 'Lecture' },
  { id: 'SEMINAR-1', name: 'Seminar Room 1', capacity: 50, type: 'Lecture' },
  { id: 'SEMINAR-2', name: 'Seminar Room 2', capacity: 45, type: 'Lecture' },
  { id: 'SEMINAR-3', name: 'Seminar Room 3', capacity: 40, type: 'Lecture' },
  { id: 'PHY-L2', name: 'Physics Lab 2', capacity: 35, type: 'Lab' },
  { id: 'PHY-L3', name: 'Physics Lab 3', capacity: 40, type: 'Lab' },
  { id: 'CHEM-L1', name: 'Chemistry Lab 1', capacity: 30, type: 'Lab' },
  { id: 'CHEM-L2', name: 'Chemistry Lab 2', capacity: 35, type: 'Lab' },
  { id: 'ED-2', name: 'Education Hall 2', capacity: 80, type: 'Lecture' },
  { id: 'ED-3', name: 'Education Hall 3', capacity: 70, type: 'Lecture' },
  { id: 'ED-SEM-1', name: 'Education Seminar 1', capacity: 40, type: 'Lecture' },
  { id: 'ED-SEM-2', name: 'Education Seminar 2', capacity: 35, type: 'Lecture' },
  { id: 'SMART-1', name: 'Smart Classroom 1', capacity: 60, type: 'Lecture' },
  { id: 'SMART-2', name: 'Smart Classroom 2', capacity: 55, type: 'Lecture' },
  { id: 'SMART-3', name: 'Smart Classroom 3', capacity: 65, type: 'Lecture' },
  { id: 'CONFERENCE-1', name: 'Conference Room 1', capacity: 30, type: 'Lecture' },
  { id: 'CONFERENCE-2', name: 'Conference Room 2', capacity: 25, type: 'Lecture' },
  { id: 'LIBRARY-1', name: 'Library Study Hall 1', capacity: 100, type: 'Lecture' },
  { id: 'LIBRARY-2', name: 'Library Study Hall 2', capacity: 80, type: 'Lecture' },
];

export const mockAlumni: Alumni[] = [
  { id: 'A001', name: 'Sneha Verma', passOutYear: 2020, achievement: 'Senior Software Engineer at Google' },
  { id: 'A002', name: 'Vikram Singh', passOutYear: 2019, achievement: 'Founder of a successful tech startup' },
  { id: 'A003', name: 'Anjali Mehta', passOutYear: 2021, achievement: 'Pursuing PhD at Stanford University' },
  { id: 'A004', name: 'Rajiv Kumar', passOutYear: 2018, achievement: 'Lead Product Manager at Microsoft' },
  { id: 'A005', name: 'Pooja Desai', passOutYear: 2022, achievement: 'Data Scientist at Amazon' },
];

export const mockResults: StudentResult[] = [
  { id: 'RES01', studentName: 'Aarav Sharma', studentId: 'S001', branch: 'Computer Science', semester: 5, sgpa: 8.9, cgpa: 9.1 },
  { id: 'RES02', studentName: 'Vivaan Singh', studentId: 'S002', branch: 'Electronics', semester: 3, sgpa: 9.2, cgpa: 9.0 },
  { id: 'RES03', studentName: 'Aditya Patel', studentId: 'S003', branch: 'Mechanical', semester: 7, sgpa: 8.1, cgpa: 8.3 },
  { id: 'RES04', studentName: 'Vihaan Verma', studentId: 'S004', branch: 'Computer Science', semester: 3, sgpa: 9.5, cgpa: 9.3 },
  { id: 'RES05', studentName: 'Arjun Jha', studentId: 'S005', branch: 'Electrical', semester: 5, sgpa: 8.7, cgpa: 8.5 },
  { id: 'RES06', studentName: 'Sai Gupta', studentId: 'S006', branch: 'Civil', semester: 7, sgpa: 7.8, cgpa: 8.1 },
  { id: 'RES07', studentName: 'Reyansh Kumar', studentId: 'S007', branch: 'Mechanical', semester: 1, sgpa: 8.5, cgpa: 8.5 },
  { id: 'RES08', studentName: 'Ayaan Reddy', studentId: 'S008', branch: 'Electronics', semester: 5, sgpa: 9.1, cgpa: 8.9 },
  { id: 'RES09', studentName: 'Krishna Iyer', studentId: 'S009', branch: 'Computer Science', semester: 1, sgpa: 9.4, cgpa: 9.4 },
  { id: 'RES10', studentName: 'Ishaan Rathod', studentId: 'S010', branch: 'Biotechnology', semester: 3, sgpa: 8.2, cgpa: 8.4 },
  { id: 'RES11', studentName: 'Rohan Mehra', studentId: 'S011', branch: 'Computer Science', semester: 5, sgpa: 8.8, cgpa: 8.9 },
  { id: 'RES12', studentName: 'Priya Agarwal', studentId: 'S012', branch: 'Electronics', semester: 1, sgpa: 9.0, cgpa: 9.0 },
  { id: 'RES13', studentName: 'Amit Desai', studentId: 'S013', branch: 'Mechanical', semester: 7, sgpa: 7.9, cgpa: 8.0 },
  { id: 'RES14', studentName: 'Sneha Khan', studentId: 'S014', branch: 'Computer Science', semester: 3, sgpa: 9.6, cgpa: 9.4 },
  { id: 'RES15', studentName: 'Karan Malhotra', studentId: 'S015', branch: 'Electrical', semester: 5, sgpa: 8.6, cgpa: 8.7 },
  { id: 'RES16', studentName: 'Ananya Joshi', studentId: 'S016', branch: 'Civil', semester: 3, sgpa: 8.0, cgpa: 8.2 },
  { id: 'RES17', studentName: 'Vikram Nair', studentId: 'S017', branch: 'Mechanical', semester: 1, sgpa: 8.3, cgpa: 8.3 },
  { id: 'RES18', studentName: 'Natasha Menon', studentId: 'S018', branch: 'Electronics', semester: 5, sgpa: 9.3, cgpa: 9.1 },
  { id: 'RES19', studentName: 'Rahul Pillai', studentId: 'S019', branch: 'Computer Science', semester: 7, sgpa: 9.7, cgpa: 9.5 },
  { id: 'RES20', studentName: 'Aryan Jain', studentId: 'S020', branch: 'Biotechnology', semester: 3, sgpa: 8.4, cgpa: 8.5 },
  { id: 'RES21', studentName: 'Siddharth Shah', studentId: 'S021', branch: 'Computer Science', semester: 5, sgpa: 9.0, cgpa: 9.2 },
  { id: 'RES22', studentName: 'Meera Chaudhary', studentId: 'S022', branch: 'Electronics', semester: 3, sgpa: 8.9, cgpa: 8.8 },
  { id: 'RES23', studentName: 'Anika Reddy', studentId: 'S023', branch: 'Mechanical', semester: 7, sgpa: 8.2, cgpa: 8.4 },
  { id: 'RES24', studentName: 'Ishita Verma', studentId: 'S024', branch: 'Computer Science', semester: 1, sgpa: 9.8, cgpa: 9.8 },
  { id: 'RES25', studentName: 'Zara Khan', studentId: 'S025', branch: 'Electrical', semester: 5, sgpa: 8.5, cgpa: 8.6 },
  { id: 'RES26', studentName: 'Kavya Singh', studentId: 'S026', branch: 'Civil', semester: 7, sgpa: 7.7, cgpa: 8.0 },
  { id: 'RES27', studentName: 'Fatima Ahmed', studentId: 'S027', branch: 'Mechanical', semester: 3, sgpa: 8.0, cgpa: 8.1 },
  { id: 'RES28', studentName: 'Jay Patel', studentId: 'S028', branch: 'Electronics', semester: 5, sgpa: 9.4, cgpa: 9.2 },
  { id: 'RES29', studentName: 'Kabir Kumar', studentId: 'S029', branch: 'Computer Science', semester: 1, sgpa: 9.3, cgpa: 9.3 },
  { id: 'RES30', studentName: 'Myra Das', studentId: 'S030', branch: 'Biotechnology', semester: 3, sgpa: 8.1, cgpa: 8.3 },
  { id: 'RES31', studentName: 'Diya Gupta', studentId: 'S031', branch: 'Computer Science', semester: 7, sgpa: 9.9, cgpa: 9.7 },
  { id: 'RES32', studentName: 'Aryan Mishra', studentId: 'S032', branch: 'Electronics', semester: 1, sgpa: 8.8, cgpa: 8.8 },
  { id: 'RES33', studentName: 'Advik Tiwari', studentId: 'S033', branch: 'Mechanical', semester: 5, sgpa: 8.3, cgpa: 8.2 },
  { id: 'RES34', studentName: 'Anvi Pandey', studentId: 'S034', branch: 'Computer Science', semester: 3, sgpa: 9.2, cgpa: 9.1 },
  { id: 'RES35', studentName: 'Aarush Bhat', studentId: 'S035', branch: 'Electrical', semester: 7, sgpa: 8.9, cgpa: 8.8 },
  { id: 'RES36', studentName: 'Kiara Hegde', studentId: 'S036', branch: 'Civil', semester: 1, sgpa: 7.9, cgpa: 7.9 },
  { id: 'RES37', studentName: 'Veer Shetty', studentId: 'S037', branch: 'Mechanical', semester: 5, sgpa: 8.4, cgpa: 8.5 },
  { id: 'RES38', studentName: 'Samaira Rao', studentId: 'S038', branch: 'Electronics', semester: 3, sgpa: 9.5, cgpa: 9.3 },
  { id: 'RES39', studentName: 'Zoya Agarwal', studentId: 'S039', branch: 'Computer Science', semester: 7, sgpa: 9.6, cgpa: 9.6 },
  { id: 'RES40', studentName: 'Dhruv Bajaj', studentId: 'S040', branch: 'Biotechnology', semester: 1, sgpa: 8.7, cgpa: 8.7 },
  { id: 'RES41', studentName: 'Riya Sharma', studentId: 'S041', branch: 'Computer Science', semester: 3, sgpa: 9.1, cgpa: 9.0 },
  { id: 'RES42', studentName: 'Arnav Singh', studentId: 'S042', branch: 'Electronics', semester: 7, sgpa: 8.8, cgpa: 8.9 },
  { id: 'RES43', studentName: 'Isha Patel', studentId: 'S043', branch: 'Mechanical', semester: 1, sgpa: 8.6, cgpa: 8.6 },
  { id: 'RES44', studentName: 'Yash Verma', studentId: 'S044', branch: 'Computer Science', semester: 5, sgpa: 9.2, cgpa: 9.1 },
  { id: 'RES45', studentName: 'Anaya Jha', studentId: 'S045', branch: 'Electrical', semester: 3, sgpa: 8.4, cgpa: 8.5 },
  { id: 'RES46', studentName: 'Nikhil Gupta', studentId: 'S046', branch: 'Civil', semester: 5, sgpa: 7.9, cgpa: 8.0 },
  { id: 'RES47', studentName: 'Parth Kumar', studentId: 'S047', branch: 'Mechanical', semester: 7, sgpa: 8.5, cgpa: 8.4 },
  { id: 'RES48', studentName: 'Saanvi Reddy', studentId: 'S048', branch: 'Electronics', semester: 1, sgpa: 9.1, cgpa: 9.1 },
  { id: 'RES49', studentName: 'Dev Iyer', studentId: 'S049', branch: 'Computer Science', semester: 3, sgpa: 9.3, cgpa: 9.2 },
  { id: 'RES50', studentName: 'Aadhya Rathod', studentId: 'S050', branch: 'Biotechnology', semester: 5, sgpa: 8.6, cgpa: 8.7 },
];

export const mockQuizMarks: QuizMark[] = [
  { id: 'QZ01', studentName: 'Aarav Sharma', studentId: 'S001', course: 'Data Structures', quizNumber: 1, marks: 18, totalMarks: 20 },
  { id: 'QZ02', studentName: 'Vivaan Singh', studentId: 'S002', course: 'Digital Circuits', quizNumber: 1, marks: 15, totalMarks: 20 },
  { id: 'QZ03', studentName: 'Aarav Sharma', studentId: 'S001', course: 'Data Structures', quizNumber: 2, marks: 19, totalMarks: 20 },
  { id: 'QZ04', studentName: 'Aditya Patel', studentId: 'S003', course: 'Thermodynamics', quizNumber: 1, marks: 22, totalMarks: 25 },
  { id: 'QZ05', studentName: 'Vihaan Verma', studentId: 'S004', course: 'Web Development', quizNumber: 1, marks: 24, totalMarks: 25 },
  { id: 'QZ06', studentName: 'Arjun Jha', studentId: 'S005', course: 'Power Electronics', quizNumber: 1, marks: 17, totalMarks: 20 },
  { id: 'QZ07', studentName: 'Vivaan Singh', studentId: 'S002', course: 'Digital Circuits', quizNumber: 2, marks: 19, totalMarks: 20 },
  { id: 'QZ08', studentName: 'Sai Gupta', studentId: 'S006', course: 'Engineering Physics', quizNumber: 1, marks: 14, totalMarks: 20 },
  { id: 'QZ09', studentName: 'Reyansh Kumar', studentId: 'S007', course: 'Creative Writing', quizNumber: 1, marks: 8, totalMarks: 10 },
  { id: 'QZ10', studentName: 'Ayaan Reddy', studentId: 'S008', course: 'Microprocessors', quizNumber: 1, marks: 21, totalMarks: 25 },
  { id: 'QZ11', studentName: 'Krishna Iyer', studentId: 'S009', course: 'Data Structures', quizNumber: 1, marks: 18, totalMarks: 20 },
  { id: 'QZ12', studentName: 'Ishaan Rathod', studentId: 'S010', course: 'Engineering Physics', quizNumber: 1, marks: 16, totalMarks: 20 },
  { id: 'QZ13', studentName: 'Rohan Mehra', studentId: 'S011', course: 'Algorithms', quizNumber: 2, marks: 23, totalMarks: 25 },
  { id: 'QZ14', studentName: 'Priya Agarwal', studentId: 'S012', course: 'Digital Circuits', quizNumber: 1, marks: 17, totalMarks: 20 },
  { id: 'QZ15', studentName: 'Amit Desai', studentId: 'S013', course: 'Fluid Mechanics', quizNumber: 1, marks: 19, totalMarks: 25 },
  { id: 'QZ16', studentName: 'Sneha Khan', studentId: 'S014', course: 'Web Development', quizNumber: 2, marks: 20, totalMarks: 25 },
  { id: 'QZ17', studentName: 'Karan Malhotra', studentId: 'S015', course: 'Power Electronics', quizNumber: 2, marks: 15, totalMarks: 20 },
  { id: 'QZ18', studentName: 'Ananya Joshi', studentId: 'S016', course: 'Creative Writing', quizNumber: 1, marks: 9, totalMarks: 10 },
  { id: 'QZ19', studentName: 'Vikram Nair', studentId: 'S017', course: 'Engineering Physics', quizNumber: 1, marks: 20, totalMarks: 25 },
  { id: 'QZ20', studentName: 'Natasha Menon', studentId: 'S018', course: 'Microprocessors', quizNumber: 2, marks: 24, totalMarks: 25 },
  { id: 'QZ21', studentName: 'Rahul Pillai', studentId: 'S019', course: 'Data Structures', quizNumber: 3, marks: 19, totalMarks: 20 },
  { id: 'QZ22', studentName: 'Aryan Jain', studentId: 'S020', course: 'Creative Writing', quizNumber: 1, marks: 9, totalMarks: 10 },
  { id: 'QZ23', studentName: 'Siddharth Shah', studentId: 'S021', course: 'Algorithms', quizNumber: 3, marks: 17, totalMarks: 20 },
  { id: 'QZ24', studentName: 'Meera Chaudhary', studentId: 'S022', course: 'Digital Circuits', quizNumber: 3, marks: 18, totalMarks: 20 },
  { id: 'QZ25', studentName: 'Anika Reddy', studentId: 'S023', course: 'Thermodynamics', quizNumber: 2, marks: 21, totalMarks: 25 },
  { id: 'QZ26', studentName: 'Ishita Verma', studentId: 'S024', course: 'Web Development', quizNumber: 1, marks: 25, totalMarks: 25 },
  { id: 'QZ27', studentName: 'Zara Khan', studentId: 'S025', course: 'Power Electronics', quizNumber: 3, marks: 16, totalMarks: 20 },
  { id: 'QZ28', studentName: 'Kavya Singh', studentId: 'S026', course: 'Fluid Mechanics', quizNumber: 2, marks: 22, totalMarks: 25 },
  { id: 'QZ29', studentName: 'Fatima Ahmed', studentId: 'S027', course: 'Thermodynamics', quizNumber: 1, marks: 13, totalMarks: 25 },
  { id: 'QZ30', studentName: 'Jay Patel', studentId: 'S028', course: 'Microprocessors', quizNumber: 3, marks: 23, totalMarks: 25 },
  { id: 'QZ31', studentName: 'Kabir Kumar', studentId: 'S029', course: 'Data Structures', quizNumber: 1, marks: 20, totalMarks: 20 },
  { id: 'QZ32', studentName: 'Myra Das', studentId: 'S030', course: 'Creative Writing', quizNumber: 1, marks: 7, totalMarks: 10 },
  { id: 'QZ33', studentName: 'Diya Gupta', studentId: 'S031', course: 'Algorithms', quizNumber: 4, marks: 19, totalMarks: 20 },
  { id: 'QZ34', studentName: 'Aryan Mishra', studentId: 'S032', course: 'Digital Circuits', quizNumber: 1, marks: 14, totalMarks: 20 },
  { id: 'QZ35', studentName: 'Advik Tiwari', studentId: 'S033', course: 'Thermodynamics', quizNumber: 3, marks: 18, totalMarks: 25 },
  { id: 'QZ36', studentName: 'Anvi Pandey', studentId: 'S034', course: 'Web Development', quizNumber: 2, marks: 22, totalMarks: 25 },
  { id: 'QZ37', studentName: 'Aarush Bhat', studentId: 'S035', course: 'Power Electronics', quizNumber: 4, marks: 18, totalMarks: 20 },
  { id: 'QZ38', studentName: 'Kiara Hegde', studentId: 'S036', course: 'Fluid Mechanics', quizNumber: 1, marks: 23, totalMarks: 25 },
  { id: 'QZ39', studentName: 'Veer Shetty', studentId: 'S037', course: 'Engineering Physics', quizNumber: 2, marks: 17, totalMarks: 20 },
  { id: 'QZ40', studentName: 'Samaira Rao', studentId: 'S038', course: 'Microprocessors', quizNumber: 4, marks: 22, totalMarks: 25 },
  { id: 'QZ41', studentName: 'Riya Sharma', studentId: 'S041', course: 'Data Structures', quizNumber: 1, marks: 19, totalMarks: 20 },
  { id: 'QZ42', studentName: 'Arnav Singh', studentId: 'S042', course: 'Digital Circuits', quizNumber: 1, marks: 16, totalMarks: 20 },
  { id: 'QZ43', studentName: 'Isha Patel', studentId: 'S043', course: 'Thermodynamics', quizNumber: 1, marks: 21, totalMarks: 25 },
  { id: 'QZ44', studentName: 'Yash Verma', studentId: 'S044', course: 'Algorithms', quizNumber: 1, marks: 23, totalMarks: 25 },
  { id: 'QZ45', studentName: 'Anaya Jha', studentId: 'S045', course: 'Power Electronics', quizNumber: 1, marks: 18, totalMarks: 20 },
  { id: 'QZ46', studentName: 'Nikhil Gupta', studentId: 'S046', course: 'Engineering Physics', quizNumber: 1, marks: 15, totalMarks: 20 },
  { id: 'QZ47', studentName: 'Parth Kumar', studentId: 'S047', course: 'Creative Writing', quizNumber: 1, marks: 9, totalMarks: 10 },
  { id: 'QZ48', studentName: 'Saanvi Reddy', studentId: 'S048', course: 'Microprocessors', quizNumber: 1, marks: 22, totalMarks: 25 },
  { id: 'QZ49', studentName: 'Dev Iyer', studentId: 'S049', course: 'Algorithms', quizNumber: 1, marks: 19, totalMarks: 20 },
  { id: 'QZ50', studentName: 'Aadhya Rathod', studentId: 'S050', course: 'Data Structures', quizNumber: 1, marks: 17, totalMarks: 20 },
];

export const mockBooks: Book[] = [
  { id: 'B001', title: 'The Art of Computer Programming', author: 'Donald Knuth', availableCopies: 5, coverImageId: 'book1' },
  { id: 'B002', title: 'Introduction to Algorithms', author: 'Thomas H. Cormen', availableCopies: 10, coverImageId: 'book2' },
  { id: 'B003', title: 'Clean Code', author: 'Robert C. Martin', availableCopies: 7, coverImageId: 'book3' },
  { id: 'B004', title: 'Design Patterns', author: 'Erich Gamma', availableCopies: 3, coverImageId: 'book4' },
  { id: 'B005', title: 'The Pragmatic Programmer', author: 'Andrew Hunt', availableCopies: 0, coverImageId: 'book5' },
  { id: 'B006', title: 'Structure and Interpretation of Computer Programs', author: 'Harold Abelson', availableCopies: 8, coverImageId: 'book6' },
  { id: 'B007', title: 'Code Complete', author: 'Steve McConnell', availableCopies: 4, coverImageId: 'book7' },
  { id: 'B008', title: 'The Mythical Man-Month', author: 'Frederick P. Brooks Jr.', availableCopies: 1, coverImageId: 'book8' },
  { id: 'B009', title: 'Refactoring: Improving the Design of Existing Code', author: 'Martin Fowler', availableCopies: 6, coverImageId: 'book9' },
  { id: 'B010', title: 'Cracking the Coding Interview', author: 'Gayle Laakmann McDowell', availableCopies: 12, coverImageId: 'book10' },
  { id: 'B011', title: 'Artificial Intelligence: A Modern Approach', author: 'Stuart Russell', availableCopies: 9, coverImageId: 'book11' },
  { id: 'B012', title: 'Compilers: Principles, Techniques, & Tools', author: 'Alfred Aho', availableCopies: 2, coverImageId: 'book12' },
  { id: 'B013', title: 'The Clean Coder', author: 'Robert C. Martin', availableCopies: 5, coverImageId: 'book13' },
  { id: 'B014', title: 'Thinking, Fast and Slow', author: 'Daniel Kahneman', availableCopies: 11, coverImageId: 'book14' },
  { id: 'B015', title: 'Sapiens: A Brief History of Humankind', author: 'Yuval Noah Harari', availableCopies: 8, coverImageId: 'book15' },
];

export const mockEditorials: Editorial[] = [
  { id: 'E001', title: 'The Future of AI in Education', author: 'Dr. Alok Mishra', publishDate: '2023-10-15', excerpt: 'Exploring the transformative potential of artificial intelligence in modern pedagogy and academic administration...', coverImageId: 'editorial1' },
  { id: 'E002', title: 'Innovations in Green Engineering', author: 'Prof. Gita Sharma', publishDate: '2023-09-28', excerpt: 'A look into the latest sustainable technologies being developed by our engineering departments...', coverImageId: 'editorial2' },
  { id: 'E003', title: 'Campus Life: A Retrospective', author: 'Student Council', publishDate: '2023-11-05', excerpt: 'A heartfelt look back at the events and activities that shaped our campus community this past year...', coverImageId: 'editorial3' },
  { id: 'E004', title: 'The Importance of Humanities in a Tech-Driven World', author: 'Dr. Priya Sharma', publishDate: '2023-11-20', excerpt: 'An argument for the continued relevance of liberal arts in fostering critical thinking and creativity.', coverImageId: 'editorial4' },
  { id: 'E005', title: 'Mental Health Awareness on Campus', author: 'Wellness Center', publishDate: '2023-12-01', excerpt: 'A guide to the resources available to students for maintaining mental well-being during stressful academic periods.', coverImageId: 'editorial5' },
];

export const mockAuditLogs: AuditLog[] = [
    {
      id: 'log-1672531200000-1',
      timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      user: 'Amritanshu Kumar',
      role: 'admin',
      action: 'USER_LOGIN',
      details: 'User logged in from IP address 192.168.1.1',
    },
    {
      id: 'log-1672534800000-2',
      timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      user: 'Dr. Anil Kumar',
      role: 'faculty',
      action: 'ATTENDANCE_MARKED',
      details: 'Marked attendance for course CS301 - Data Structures.',
    },
    {
      id: 'log-1672538400000-3',
      timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      user: 'Amritanshu Kumar',
      role: 'admin',
      action: 'CONSTRAINT_CHANGE',
      details: 'Updated room capacity for R101 to 75.',
    },
];

    